steps:
  # 1. Dockerイメージのビルド (COMMIT_SHAとlatestの両方をタグ付け)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-app-repo/helloslackbolt:$BUILD_ID'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-app-repo/helloslackbolt:latest'
      - '.'

  # 2. Artifact Registryへのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-app-repo/helloslackbolt:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-app-repo/helloslackbolt:latest'

  # 3. Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'helloslackbolt'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-app-repo/helloslackbolt:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'                # 対話型プロンプトを無効にする
      # 全環境変数の設定
      - '--env-vars-file'
      - 'env_vars.yaml'
      # シークレットを /secrets/client_secret.json としてマウントする設定
      - '--update-secrets'
      - '/secrets/client_secret.json=GOOGLE_CLIENT_SECRET_JSON:latest'
      # # サービスアカウントの設定 (JSON鍵を使わないADC方式)　デフォルトのサービスアカウントを利用しない場合はこの設定が必要
      # - '--service-account'
      # - 'helloslackbolt@$PROJECT_ID.iam.gserviceaccount.com'
      # リソース制限
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '60s'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-app-repo/helloslackbolt:$BUILD_ID'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-app-repo/helloslackbolt:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  # machineType: 'E2_HIGHCPU_8'

timeout: 1200s